<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>비동기 처리</title>
</head>

<body>
    <script>

        //콜백함수(콜백지옥)
        function increase(number, callback) {
            setTimeout(() => {
                const result = number + 10;
                if (callback) {
                    callback(result);
                }
            }, 1000);
        }

        console.log('작업 시작');
        increase(0, result => {
            console.log(result);
            increase(result, result => {
                console.log(result);
                increase(result, result => {
                    console.log(result);
                    increase(result, result => {
                        console.log(result);
                        console.log('작업 완료');
                    });
                });
            });
        });

        //Promise는 콜백 지옥 같은 코드가 형성되지 않게 하는 방안으로 ES6에 도입된 기능

        function increase(number) {
            const promise = new Promise((resolve, reject) => {
                // resolve는 성공, reject는 실패
                setTimeout(() => {
                    const result = number + 10;
                    if (result > 50) {
                        // 50보다 높으면 에러 발생시키기
                        const e = new Error('NumberTooBig');
                        return reject(e);
                    }
                    resolve(result); // number 값에 +10 후 성공 처리
                }, 1000);
            });
            return promise;
        }

        increase(0)
            .then(number => {
                // Promise에서 resolve된 값은 .then을 통해 받아 올 수 있음
                console.log(number);
                return increase(number); // Promise를 리턴하면
            })
            .then(number => {
                // 또 .then으로 처리 가능
                console.log(number);
                return increase(number);
            })
            .then(number => {
                console.log(number);
                return increase(number);
            })
            .then(number => {
                console.log(number);
                return increase(number);
            })
            .then(number => {
                console.log(number);
                return increase(number);
            })
            .catch(e => {
                // 도중에 에러가 발생한다면 .catch를 통해 알 수 있음
                console.log(e);
            });

        // async/await는 Promise를 더욱 쉽게 사용할 수 있도록 해 주는 ES2017(ES8) 문법

        function increase(number) {
            const promise = new Promise((resolve, reject) => {
                // resolve는 성공, reject는 실패
                setTimeout(() => {
                    const result = number + 10;
                    if (result > 50) { // 50보다 높으면 에러 발생시키기
                        const e = new Error('NumberTooBig');
                        return reject(e);
                    }
                    resolve(result); // number 값에 +10 후 성공 처리
                }, 1000)
            });
            return promise;
        }

        async function runTasks() {
            try { // try/catch 구문을 사용하여 에러를 처리합니다.
                let result = await increment(0);
                console.log(result);
                result = await increment(result);
                console.log(result);
                result = await increment(result);
                console.log(result);
                result = await increment(result);
                console.log(result);
                result = await increment(result);
                console.log(result);
                result = await increment(result);
                console.log(result);
            } catch (e) {
                console.log(e);
            }
        }
    </script>

</body>

</html>